// CREATE BUCKET FROM RESUME STORED IN BUCKET --> ROUTES
// /admin/:userId/process

// INPUT(TEMPLATE_ID, USER_ID, RESUME)
// DOWNLOAD RESUME FROM BUCKET
// STORE LOCALLY
// EXTRACT TEXT FROM PDF
// ORDER THE TEXT
// CREATE PROJECTS, EDUCATION, EXPERIENCE FROM TEXT
// CREATE BUCKET WITH TEMPLATE 
// UPLOAD REACT APP TO BUCKET
// RETURN S3URL TO WEBSITE

